#!/bin/bash

## colors
red="\e[1;31m"
green="\e[1;32m"
brown="\e[1;33m" # (Yellow)
blue="\e[1;34m"  # (Orange)
violet="\e[1;35m"
cyan="\e[1;36m"
colnull="\e[0m"

## Wallart

echo "   ▄████████ ███    █▄     ▄███████▄    ▄████████ "
echo "  ███    ███ ███    ███   ███    ███   ███    ███ "
echo "  ███    █▀  ███    ███   ███    ███   ███    █▀  "
echo "  ███        ███    ███   ███    ███   ███        "
echo "▀███████████ ███    ███ ▀█████████▀  ▀███████████ "
echo "         ███ ███    ███   ███                 ███ "
echo "   ▄█    ███ ███    ███   ███           ▄█    ███ "
echo " ▄████████▀  ████████▀   ▄████▀       ▄████████▀  "
echo ""
echo ""

## Code


if [ -z "$2" ]
then
    delay=3600
else
    delay=$2
fi


if [ -z "$1" ]
then
    echo -e "$red[!]$colnull Empty Arguments"
    exit 0
fi

echo -e "$blue[?]$colnull First Check..."
echo -en "$brown[i]$colnull"
date "+ %d/%m/%y %H:%M:%S"
sha1=$(curl -s "$1" | sha512sum)
echo -e "$brown[i]$colnull Sha: $sha1"
while [ 1 ];
do
    echo ""
	echo -e "$blue[?]$colnull Starting Recheck..."
	echo -en "$brown[i]$colnull"
    date "+ %d/%m/%y %H:%M:%S"
	sha2=$(curl -s "$1" | sha512sum)
	echo -e "$brown[i]$colnull Sha: $sha2"
	if [ "$sha1" != "$sha2" ]
	then
		echo -e "$blue[?]$colnull Double Checking"
		sleep 5
		check=$(curl -s "$1" | sha512sum)
		if [ "$check" == "$sha1" ]
		then
			echo -e "$red[!]$colnull Was probably a bad response"
            echo -e "$red[!]$colnull Nothing changed"
            sha2="$check"
		else
			echo -e "$green[!]$colnull THE SITE WAS UPDATED"
		fi
    else
        echo -e "$red[!]$colnull Nothing changed"
	fi
	sha1="$sha2"
	sleep $delay
done
