#!/bin/bash

echo "first check"
sha1=$(curl -s "$1" | sha512sum)
echo "$sha1"
while [ 1 ];
do
	echo ""
	echo ""
	echo "rechecking..."
	date
	sha2=$(curl -s "$1" | sha512sum)
	echo "$sha2"
	if [ "$sha1" != "$sha2" ]
	then
		echo "double checking..."
		sleep 5
		check=$(curl -s "$1" | sha512sum)
		if [ "$check" == "$sha1"]
		then
			echo ""
			echo "probably bad response"
		else
			echo ""
			echo "SITO AGGIORNATO!"
			date
		fi
	fi
	sha1="$sha2"
	sleep 600
done
